import { IsOptional, Allow } from 'class-validator';

export class CreateProductDto {
  @Allow() @IsOptional() title?: any;
  @Allow() @IsOptional() name?: any;
  @Allow() @IsOptional() brand?: any;
  @Allow() @IsOptional() urlSlug?: any;
  @Allow() @IsOptional() sku?: any;
  @Allow() @IsOptional() category?: any;
  @Allow() @IsOptional() buyingPrice?: any;
  @Allow() @IsOptional() price?: any;
  @Allow() @IsOptional() comparePrice?: any;
  @Allow() @IsOptional() deliveryInsideDhaka?: any;
  @Allow() @IsOptional() deliveryOutsideDhaka?: any;
  @Allow() @IsOptional() stock?: any;
  @Allow() @IsOptional() lowStockThreshold?: any;
  @Allow() @IsOptional() status?: any;
  @Allow() @IsOptional() image?: any;
  @Allow() @IsOptional() galleryImages?: any;
  @Allow() @IsOptional() shortDescription?: any;
  @Allow() @IsOptional() description?: any;
  @Allow() @IsOptional() usability?: any;
  @Allow() @IsOptional() features?: any;
  @Allow() @IsOptional() specifications?: any;
  @Allow() @IsOptional() color?: any;
  @Allow() @IsOptional() material?: any;
  @Allow() @IsOptional() warranty?: any;
  @Allow() @IsOptional() variantName?: any;
  @Allow() @IsOptional() variantOptions?: any;
  @Allow() @IsOptional() metaTitle?: any;
  @Allow() @IsOptional() metaDescription?: any;
  @Allow() @IsOptional() seoKeywords?: any;
  @Allow() @IsOptional() keywords?: any;
  @Allow() @IsOptional() tags?: any;
}

export class UpdateProductDto {
  @Allow() @IsOptional() title?: any;
  @Allow() @IsOptional() name?: any;
  @Allow() @IsOptional() brand?: any;
  @Allow() @IsOptional() urlSlug?: any;
  @Allow() @IsOptional() sku?: any;
  @Allow() @IsOptional() category?: any;
  @Allow() @IsOptional() buyingPrice?: any;
  @Allow() @IsOptional() price?: any;
  @Allow() @IsOptional() comparePrice?: any;
  @Allow() @IsOptional() deliveryInsideDhaka?: any;
  @Allow() @IsOptional() deliveryOutsideDhaka?: any;
  @Allow() @IsOptional() stock?: any;
  @Allow() @IsOptional() lowStockThreshold?: any;
  @Allow() @IsOptional() status?: any;
  @Allow() @IsOptional() image?: any;
  @Allow() @IsOptional() galleryImages?: any;
  @Allow() @IsOptional() shortDescription?: any;
  @Allow() @IsOptional() description?: any;
  @Allow() @IsOptional() usability?: any;
  @Allow() @IsOptional() features?: any;
  @Allow() @IsOptional() specifications?: any;
  @Allow() @IsOptional() color?: any;
  @Allow() @IsOptional() material?: any;
  @Allow() @IsOptional() warranty?: any;
  @Allow() @IsOptional() variantName?: any;
  @Allow() @IsOptional() variantOptions?: any;
  @Allow() @IsOptional() metaTitle?: any;
  @Allow() @IsOptional() metaDescription?: any;
  @Allow() @IsOptional() seoKeywords?: any;
  @Allow() @IsOptional() keywords?: any;
  @Allow() @IsOptional() tags?: any;
}
